"use client";

import { ArrowLeftRight, Boxes, ClipboardCheck, PackageCheck, Plus, RotateCcw, Save, ScanBarcode, Tags } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { BarcodeInput } from "@/components/barcode-input";

type ProductOption = { id: string; name: string; barcode?: string | null; unit: string; quantity?: number };
type LocationOption = { id: string; name: string; type: "STORE" | "WAREHOUSE"; isDefault: boolean };
type PurchaseOrderOption = { id: string; label: string; items: Array<{ productId: string; name: string; barcode: string | null; remaining: number; unitCost: number }> };
type ListingOption = { id: string; name: string; price: number; minOrderQty: number };
type CustomerOption = { id: string; name: string };
type PickingOrder = { id: string; buyerName: string; totalItems: number };

function Feedback({ message, error }: { message: string; error: string }) {
  if (!message && !error) return null;
  return <div className="infoNote" style={{ color: error ? "#9b3028" : "#176b3a", background: error ? "#fff0ef" : "#edf8f1" }}>{error || message}</div>;
}

export function LocationCreateForm() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setMessage(""); setError("");
    const form = new FormData(event.currentTarget);
    const response = await fetch("/api/inventory/locations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), type: form.get("type"), isDefault: form.get("isDefault") === "on" }) });
    const result = await response.json().catch(() => ({})); setLoading(false);
    if (!response.ok) return setError(result.error === "INVALID_INPUT" ? "راجع اسم الموقع ونوعه." : "تعذر إنشاء الموقع.");
    event.currentTarget.reset(); setMessage("تم إنشاء الموقع وربطه بالمخزون."); router.refresh();
  }
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">موقع جديد</span><h2>إضافة فرع أو مستودع</h2></div><Boxes size={20} /></div><div className="marketFormGrid"><label>الاسم<input name="name" required placeholder="مثال: فرع الروضة" /></label><label>النوع<select name="type" defaultValue="STORE"><option value="STORE">فرع / متجر</option><option value="WAREHOUSE">مستودع</option></select></label></div><label className="toggleRow"><input name="isDefault" type="checkbox" /> اجعله الموقع الافتراضي للكاشير والاستلام</label><Feedback message={message} error={error} /><button className="button primary" disabled={loading}><Plus size={17} /> {loading ? "جاري الحفظ..." : "إضافة الموقع"}</button></form>;
}

export function StockTransferForm({ locations, products }: { locations: LocationOption[]; products: ProductOption[] }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/inventory/transfers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sourceLocationId: form.get("sourceLocationId"), destinationLocationId: form.get("destinationLocationId"), productId: form.get("productId"), quantity: Number(form.get("quantity")), note: form.get("note") || undefined }) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError(result.error?.startsWith?.("INSUFFICIENT_LOCATION_STOCK") ? "الكمية في الموقع المصدر غير كافية." : "تعذر تنفيذ التحويل."); setMessage("تم نقل الكمية بين المواقع بدون تغيير إجمالي مخزون المنشأة."); event.currentTarget.reset(); router.refresh(); }
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">تحويل داخلي</span><h2>نقل بضاعة بين الفروع والمستودعات</h2></div><ArrowLeftRight size={20} /></div><div className="marketFormGrid"><label>من<select name="sourceLocationId" required defaultValue={locations[0]?.id}>{locations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>إلى<select name="destinationLocationId" required defaultValue={locations[1]?.id || ""}><option value="" disabled>اختر الموقع</option>{locations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الصنف<select name="productId" required defaultValue=""><option value="" disabled>اختر الصنف</option>{products.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الكمية<input name="quantity" type="number" min="0.001" step="0.001" required inputMode="decimal" /></label><label className="full">ملاحظة<input name="note" placeholder="اختياري" /></label></div><Feedback message={message} error={error} /><button className="button primary" disabled={loading || locations.length < 2}><ArrowLeftRight size={17} /> {loading ? "جاري التحويل..." : "تنفيذ التحويل"}</button></form>;
}

export function ReturnForm({ products, locations }: { products: ProductOption[]; locations: LocationOption[] }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const serials = String(form.get("serials") || "").split(/[\n,]+/).map((x) => x.trim()).filter(Boolean); const response = await fetch("/api/inventory/returns", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productId: form.get("productId"), quantity: Number(form.get("quantity")), type: form.get("type"), locationId: form.get("locationId"), reason: form.get("reason") || undefined, serials: serials.length ? serials : undefined }) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError(result.error?.startsWith?.("INSUFFICIENT") ? "المخزون غير كافٍ لهذه العملية." : "تعذر تسجيل المرتجع."); setMessage("تم تسجيل المرتجع وتحديث المخزون وسجل الحركة."); event.currentTarget.reset(); router.refresh(); }
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">المرتجعات</span><h2>عميل، مورد أو تالف</h2></div><RotateCcw size={20} /></div><div className="marketFormGrid"><label>النوع<select name="type" defaultValue="CUSTOMER_RETURN"><option value="CUSTOMER_RETURN">مرتجع من عميل — يزيد المخزون</option><option value="SUPPLIER_RETURN">مرتجع إلى المورد — ينقص المخزون</option><option value="DAMAGED">تالف / غير صالح — ينقص المخزون</option></select></label><label>الموقع<select name="locationId" defaultValue={locations.find((x) => x.isDefault)?.id || locations[0]?.id}>{locations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الصنف<select name="productId" required defaultValue=""><option value="" disabled>اختر الصنف</option>{products.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الكمية<input name="quantity" type="number" min="0.001" step="0.001" required /></label><label className="full">السبب<input name="reason" placeholder="مثال: عيب مصنعي / طلب العميل" /></label><label className="full">Serial / IMEI إن وجد<textarea name="serials" rows={2} placeholder="رقم في كل سطر أو مفصول بفاصلة" /></label></div><Feedback message={message} error={error} /><button className="button primary" disabled={loading}><RotateCcw size={17} /> {loading ? "جاري التسجيل..." : "اعتماد المرتجع"}</button></form>;
}

export function UnitConversionForm({ products }: { products: ProductOption[] }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/inventory/unit-conversions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productId: form.get("productId"), name: form.get("name"), factor: Number(form.get("factor")), barcode: form.get("barcode") || undefined, salePrice: form.get("salePrice") ? Number(form.get("salePrice")) : null }) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError("تعذر حفظ وحدة البيع."); setMessage("تم حفظ الوحدة. الكاشير سيخصم معاملها من وحدة المخزون الأساسية."); event.currentTarget.reset(); router.refresh(); }
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">وحدات البيع</span><h2>حبة، باك، كرتون أو وزن</h2></div><Tags size={20} /></div><div className="marketFormGrid"><label>الصنف<select name="productId" required defaultValue=""><option value="" disabled>اختر الصنف</option>{products.map((x) => <option key={x.id} value={x.id}>{x.name} · الأساس {x.unit}</option>)}</select></label><label>اسم الوحدة<input name="name" required placeholder="مثال: كرتون" /></label><label>كم تساوي من الوحدة الأساسية؟<input name="factor" type="number" min="0.001" step="0.001" required placeholder="مثال: 24" /></label><label>سعر الوحدة الجديدة<input name="salePrice" type="number" min="0" step="0.01" placeholder="اختياري" /></label><div className="full"><BarcodeInput name="barcode" /></div></div><Feedback message={message} error={error} /><button className="button primary" disabled={loading}><Save size={17} /> {loading ? "جاري الحفظ..." : "حفظ وحدة البيع"}</button></form>;
}

export function SmartReceivingForm({ orders, locations }: { orders: PurchaseOrderOption[]; locations: LocationOption[] }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const productId = String(form.get("productId") || "") || undefined; const response = await fetch("/api/inventory/receiving", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ purchaseOrderId: form.get("purchaseOrderId"), productId, barcode: form.get("barcode") || undefined, receivedQty: Number(form.get("receivedQty")), unitCost: form.get("unitCost") ? Number(form.get("unitCost")) : undefined, locationId: form.get("locationId"), invoiceNumber: form.get("invoiceNumber") || undefined, lotNumber: form.get("lotNumber") || undefined, expiryDate: form.get("expiryDate") || undefined, serials: String(form.get("serials") || "").split(/[\n,]+/).map((x) => x.trim()).filter(Boolean) }) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError(result.error === "RECEIVED_QTY_EXCEEDS_ORDER" ? `الكمية أكبر من المتبقي (${result.remaining ?? 0}).` : result.error === "SERIAL_COUNT_MISMATCH" ? `عدد أرقام Serial يجب أن يساوي ${result.expected}.` : "تعذر تسجيل الاستلام."); setMessage(`تم استلام ${result.item?.productName || "الصنف"}. المتبقي ${result.item?.remaining ?? 0}.`); event.currentTarget.reset(); router.refresh(); }
  const allItems = orders.flatMap((order) => order.items.map((item) => ({ ...item, orderId: order.id })));
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">استلام ذكي</span><h2>امسح الصنف وقارن المطلوب بالمستلم</h2></div><PackageCheck size={20} /></div><div className="marketFormGrid"><label>طلب الشراء<select name="purchaseOrderId" required defaultValue=""><option value="" disabled>اختر الطلب</option>{orders.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>الموقع<select name="locationId" defaultValue={locations.find((x) => x.isDefault)?.id || locations[0]?.id}>{locations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>اختيار يدوي للصنف<select name="productId" defaultValue=""><option value="">أو استخدم الباركود</option>{allItems.map((x) => <option key={`${x.orderId}-${x.productId}`} value={x.productId}>{x.name} · متبقي {x.remaining}</option>)}</select></label><label>الكمية المستلمة<input name="receivedQty" type="number" min="0.001" step="0.001" required /></label><div className="full"><BarcodeInput name="barcode" /></div><label>تكلفة الوحدة<input name="unitCost" type="number" min="0" step="0.01" placeholder="يستخدم سعر الطلب إذا تركته" /></label><label>رقم الفاتورة<input name="invoiceNumber" placeholder="اختياري" /></label><label>رقم الدفعة<input name="lotNumber" placeholder="اختياري" /></label><label>تاريخ الصلاحية<input name="expiryDate" type="date" /></label><label className="full">Serial / IMEI للأجهزة<textarea name="serials" rows={2} placeholder="رقم لكل قطعة — اختياري" /></label></div><Feedback message={message} error={error} /><button className="button primary" disabled={loading || !orders.length}><ScanBarcode size={17} /> {loading ? "جاري الاستلام..." : "تسجيل الاستلام"}</button></form>;
}

export function ShiftManager({ openShift, defaultLocationId }: { openShift: { id: string; openingCash: number; openedAt: string } | null; defaultLocationId: string }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const payload = openShift ? { action: "CLOSE", shiftId: openShift.id, actualCash: Number(form.get("actualCash")), note: form.get("note") || undefined } : { action: "OPEN", locationId: defaultLocationId, openingCash: Number(form.get("openingCash") || 0) }; const response = await fetch("/api/shifts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError(result.error === "SHIFT_ALREADY_OPEN" ? "توجد وردية مفتوحة بالفعل." : "تعذر تحديث الوردية."); if (openShift && result.summary) setMessage(`تم الإقفال. المتوقع ${result.summary.expectedCash.toFixed(2)} ر.س، الفعلي ${result.summary.actualCash.toFixed(2)} ر.س، الفرق ${result.summary.difference.toFixed(2)} ر.س.`); else setMessage("تم فتح الوردية وبدأ احتساب مبيعاتها."); router.refresh(); }
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">الوردية</span><h2>{openShift ? "إقفال الوردية الحالية" : "فتح وردية جديدة"}</h2></div><ClipboardCheck size={20} /></div>{openShift ? <div className="marketFormGrid"><label>النقد الفعلي عند الإقفال<input name="actualCash" type="number" min="0" step="0.01" required /></label><label>ملاحظة<input name="note" placeholder="اختياري" /></label></div> : <div className="marketFormGrid"><label>رصيد الصندوق الافتتاحي<input name="openingCash" type="number" min="0" step="0.01" defaultValue="0" /></label></div>}<Feedback message={message} error={error} /><button className="button primary" disabled={loading}><ClipboardCheck size={17} /> {loading ? "جاري الحفظ..." : openShift ? "إقفال الوردية" : "فتح الوردية"}</button></form>;
}

export function PriceTierForm({ listings, customers }: { listings: ListingOption[]; customers: CustomerOption[] }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/marketplace/listings/price-tiers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ listingId: form.get("listingId"), minQty: Number(form.get("minQty")), price: Number(form.get("price")), customerBusinessId: form.get("customerBusinessId") || undefined, validUntil: form.get("validUntil") || undefined }) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError("تعذر إضافة مستوى السعر."); setMessage("تم حفظ السعر وسيطبّق تلقائيًا على الطلبات المطابقة."); event.currentTarget.reset(); router.refresh(); }
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">تسعير المورد</span><h2>سعر حسب الكمية أو التاجر</h2></div><Tags size={20} /></div><div className="marketFormGrid"><label>المنتج<select name="listingId" required defaultValue=""><option value="" disabled>اختر المنتج</option>{listings.map((x) => <option key={x.id} value={x.id}>{x.name} · السعر الحالي {x.price.toFixed(2)}</option>)}</select></label><label>من كمية<input name="minQty" type="number" min="0.001" step="0.001" required /></label><label>السعر الجديد<input name="price" type="number" min="0.01" step="0.01" required /></label><label>تاجر محدد<select name="customerBusinessId" defaultValue=""><option value="">كل التجار</option>{customers.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>صالح حتى<input name="validUntil" type="date" /></label></div><Feedback message={message} error={error} /><button className="button primary" disabled={loading}><Tags size={17} /> {loading ? "جاري الحفظ..." : "إضافة سعر"}</button></form>;
}

export function PickingForm({ orders }: { orders: PickingOrder[] }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const orderId = String(form.get("orderId")); const response = await fetch(`/api/marketplace/orders/${orderId}/pick`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ barcode: form.get("barcode") }) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError(result.error === "BARCODE_NOT_IN_ORDER" ? "هذا الباركود غير موجود في الطلب." : result.error === "ITEM_ALREADY_COMPLETE" ? "تم تجهيز الكمية المطلوبة من هذا الصنف." : "تعذر تسجيل المسح."); setMessage(result.orderComplete ? "اكتمل تجهيز الطلب بالكامل ✅" : `${result.item?.name}: ${result.item?.scanned}/${result.item?.required}`); event.currentTarget.reset(); router.refresh(); }
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">تجهيز بالمسح</span><h2>لا يمر صنف غير موجود في الطلب</h2></div><ScanBarcode size={20} /></div><div className="marketFormGrid"><label>الطلب<select name="orderId" required defaultValue=""><option value="" disabled>اختر الطلب</option>{orders.map((x) => <option key={x.id} value={x.id}>{x.buyerName} · {x.totalItems} وحدة</option>)}</select></label><div className="full"><BarcodeInput name="barcode" /></div></div><Feedback message={message} error={error} /><button className="button primary" disabled={loading || !orders.length}><ScanBarcode size={17} /> {loading ? "جاري التحقق..." : "تسجيل المسح"}</button></form>;
}

export function ProductConfigForm({ products, businessActivity }: { products: ProductOption[]; businessActivity: string }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/inventory/product-config", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productId: form.get("productId"), saleMode: form.get("saleMode"), size: form.get("size") || undefined, color: form.get("color") || undefined, variantGroup: form.get("variantGroup") || undefined }) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError("تعذر حفظ إعداد الصنف."); setMessage("تم حفظ طريقة البيع وسيستخدمها الكاشير."); router.refresh(); }
  const defaultMode = businessActivity === "ELECTRONICS" ? "SERIAL" : businessActivity === "RESTAURANT" || businessActivity === "CAFE" ? "RECIPE" : "STANDARD";
  return <form className="panel marketForm" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">تخصيص النشاط</span><h2>طريقة بيع كل صنف</h2></div><Save size={20} /></div><div className="marketFormGrid"><label>الصنف<select name="productId" required defaultValue=""><option value="" disabled>اختر الصنف</option>{products.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>طريقة البيع<select name="saleMode" defaultValue={defaultMode}><option value="STANDARD">قطعة / كمية عادية</option><option value="WEIGHT">وزن وكسور</option><option value="SERIAL">قطعة برقم Serial / IMEI</option><option value="RECIPE">وصفة / وجبة</option><option value="SERVICE">خدمة بدون مخزون</option></select></label><label>المقاس<input name="size" placeholder="للملابس مثل L أو 42" /></label><label>اللون<input name="color" placeholder="للملابس أو المنتجات المتغيرة" /></label><label className="full">مجموعة المتغيرات<input name="variantGroup" placeholder="مثال: تيشيرت موديل 2026" /></label></div><Feedback message={message} error={error} /><button className="button primary" disabled={loading}><Save size={17} /> {loading ? "جاري الحفظ..." : "حفظ إعداد الصنف"}</button></form>;
}
